import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactNode } from 'react'

const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  weight: "400 900",
  style: "normal",
  display: "swap",
  preload: true,
  fallback: ["system-ui", "sans-serif"],
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="kr">
      <body className={`${pretendard.className} font-sans tracking-tight`}>
        <div className="min-h-screen bg-white text-black">
          {children}
        </div>
      </body>
    </html>
  )
}
